"""import batch staging columns

Revision ID: 92fd5f2f2490
Revises: adb942d481de
Create Date: 2026-08-19 16:06:28.142181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92fd5f2f2490'
down_revision: Union[str, Sequence[str], None] = 'adb942d481de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_batches', sa.Column('staged_columns', sa.JSON(), nullable=True))
    op.add_column('import_batches', sa.Column('staged_rows', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_batches', 'staged_rows')
    op.drop_column('import_batches', 'staged_columns')
    # ### end Alembic commands ###
